account/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^customerlogin/(?P<customerId>\w*)$', views.customer_login, name="customer_login"),
    url(r'^login/$', views.user_login, name="user_login"),
    url(r'^checkcode.html$', views.getcheck_code),
]

myNFCProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^favicon.ico$', RedirectView.as_view(url=r'static/favicon.ico')),
    url(r'^nfcenter/', include('warehouse.urls', namespace='warehouse', app_name='warehouse')),
    url(r'^account/', include("account.urls", namespace='account', app_name='account')),
]

warehouse/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
]

warehouse/models.py
from django.db import models
from django.utils import timezone
# from django.utils.deconstruct import deconstructible
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User

# Create your models here.
class Customer(models.Model):
    customer = models.CharField(max_length=16, primary_key=True)
    customerName = models.CharField(max_length=64)
    address = models.CharField(max_length=1024)
    phone = models.CharField(max_length=32)
    email = models.CharField(max_length=64)
    employeeID = models.ForeignKey(User, related_name="account_creator")
    createTime = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.customer

# when create a customer, create a customer account automatically at same time
class CustomerAccount(models.Model):
    customer = models.OneToOneField("Customer", auto_created=True, on_delete=models.CASCADE, primary_key=True)
    customerUserName = models.CharField(max_length=64, default="customer")
    customerPassword = models.CharField(max_length=128, default="666666")

    def __str__(self):
        return self.customerUserName

# 客户开店
class Store(models.Model):
    store = models.CharField(max_length=16, primary_key=True)
    storeName = models.CharField(max_length=128)
    customerID = models.ForeignKey("Customer", related_name="store_owner", on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.store

# 店铺内上架商品
class Product(models.Model):
    product = models.CharField(max_length=16, primary_key=True)
    productName = models.CharField(max_length=128)
    # 店铺内展示商品数量
    productAmount = models.PositiveIntegerField(verbose_name="product_inventory", default=0)
    # 商品所在的店铺
    store = models.ManyToManyField("Store")

    def __str__(self):
        return self.product

# 商品详情
class ProductDetail(models.Model):
    product = models.OneToOneField("Product", auto_created=True, on_delete=models.CASCADE, primary_key=True, default=None)
    color = models.CharField(max_length=32)
    style = models.CharField(max_length=64)
    size = models.CharField(max_length=32)

# 用户下单, 客户接到相应的订单
# 是将订单交给 warehouse 处理 或 某个其他供应商
class Orders(models.Model):
    SUPPLIER_CHOICES = [
        ('WH', "WAREHOUSE"),
        ('ETC', "OTHERS")
    ]
    order = models.OneToOneField("EndUserOrders", auto_created=True, primary_key=True)
    supplier = models.CharField(max_length=3, choices=SUPPLIER_CHOICES, default='WH')
    # 如果 supplier 为 warehouse 则将订单交给 warehouse 这时 logistics 为 null
    # 一张订单可能涉及到多个物流信息, 一个物流信息可能包含多个订单， 所以是多对多的关系
    logistics = models.ManyToManyField("Logistics")


# 物流信息
class Logistics(models.Model):
    # 物流单号
    logistics = models.CharField(max_length=128, primary_key=True)
    # 联系人， 地址， 电话
    contact = models.CharField(max_length=64)
    address = models.CharField(max_length=256)
    phone = models.CharField(max_length=11, validators=[MinLengthValidator(11)])
    # 物流费用
    rate = models.DecimalField(verbose_name="费用", max_digits=5, decimal_places=2)
    # 物品信息
    goods = models.ForeignKey("GoodsInfo")


# 物品信息
class GoodsInfo(models.Model):
    type = models.CharField(max_length=32, default='general')
    size = models.DecimalField(max_digits=5, decimal_places=2)
    weight = models.DecimalField(max_digits=7, decimal_places=2)

# 物流信息
class LogisticsInfo(models.Model):
    logistics = models.OneToOneField("Logistics", auto_created=True, primary_key=True)
    # 物品当前所在位置
    currentPosition = models.CharField(max_length=256)
    currentTime = models.DateTimeField(default=timezone.now)
    # 预计到达时间 以小时为单位
    estimateArrivalTime = models.DecimalField(default=0, max_digits=5, decimal_places=1)

# 上架的商品
'''
class StoreProduct(models.Model):
    storeID = models.ForeignKey(Store, on_delete=models.CASCADE, default=None, primary_key=True)
    productID = models.ForeignKey(Product, on_delete=models.CASCADE, default=None, primary_key=True)
'''

# 存放商品的仓库 客户将商品发到仓库保存便于发货
class Warehouse(models.Model):
    warehouse = models.CharField(max_length=16, primary_key=True)
    warehouseName = models.CharField(max_length=64)
    warehouseLocation = models.CharField(max_length=128, unique=True)

# 商品放入warehouse的库存清单中
class Inventory(models.Model):
    inventory = models.CharField(max_length=16, primary_key=True)
    product = models.ForeignKey("Product")
    # 入库商品数量
    inventoryProductAmount = models.IntegerField(default=0)
    location = models.ForeignKey("Warehouse", to_field="warehouseLocation", related_name="product_inventory_location")

    def __str__(self):
        return self.inventory

# 当客户将订单发给 warehouse, warehouse 会处理相应的订单
# warehouse 将货物交由物流公司进行运输
class WarehouseOrders(models.Model):
    order = models.OneToOneField("Orders", primary_key=True)
    logistics = models.ManyToManyField("Logistics")


# 终端用户
class EndUser(models.Model):
    user = models.CharField(max_length=16)
    userName = models.CharField(max_length=128)
    password = models.CharField(max_length=128)

# 用户个人资料
class EndUserProfile(models.Model):
    user = models.OneToOneField("EndUser", primary_key=True)
    gender = models.BooleanField(default=True)
    birth = models.DateField(default=timezone.now)
    address = models.CharField(max_length=512, null=True)
    phone = models.CharField(max_length=11, validators=[MinLengthValidator(11)])

# 用户下单
class EndUserOrders(models.Model):
    order = models.CharField(max_length=16, primary_key=True)
    # 下单的用户
    user = models.ForeignKey("EndUser")
    # 订单配送地址
    delivery_address = models.CharField(max_length=512)
    # 联系电话
    phone = models.CharField(max_length=11, validators=[MinLengthValidator(11)])
    # 下单的商品
    product = models.ForeignKey("Product")

warehouse/views.py
from django.shortcuts import render
from .models import Customer, CustomerAccount

# Create your views here.
def index(request):
    # customers = Customer.objects.all()
    return render(request, "warehouse/index.html")

def customerLogin(request, customerID):
    # customer = CustomerAccount.objects.get(id=customerID)
    return render(request, "warehouse/customerLogin.html", {"customer": customerID})

templates/warehouse/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"">
</head>
<body>
    {% include "warehouse/header.html" %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {% include "warehouse/footer.html" %}
    {% block javascript %} {% endblock %}
</body>
</html>

templates/warehouse/customerLogin.html
{% extends "warehouse/base.html"%}

{% block title %}Customer Login Page{% endblock %}

{% block content %}

<div class="row text-center vertical-middle-sm">
    <h1> Customer Login</h1>
</div>
<h1>{{ customer }}</h1>
{% endblock %}

templates/warehouse/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy right www.nfcenter.com</p>
</div>

templates/warehouse/header.html
{% load staticfiles %}
<div class="container">
    <nav class="nav nav-default" role="navigation">
        <div class="navbar-header">
            <a href="{% url 'warehouse:index' %}}" class="navbar-brand">
                <img src="{% static '/images/logo.png' %}" alt="logo" width="100px">
            </a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="#">Customer</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">LOGIN</a></li>
            </ul>
        </div>
    </nav>
</div>

templates/warehouse/index.html
{% extends "warehouse/base.html" %}

{% block title %}NFC{% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1> Welcome to Newark Filfullment Center Customer Management</h1>
</div>

{% endblock %}